<?php
  echo $this->docType(); 
?>
  <head>
    <?php
      echo $this->title();
      echo $this->getStyles();
      echo $this->getScripts();
    ?>
  </head>
  <body>
    <div id="lynx_wrapper">
      <div id="header">Lynx RAD PHP Framework</div>
      <div id="content">
	    <?php
	       $this->renderPartial(Lynx_Request::getInstance()->currentAction());
	    ?>
      </div>
      <div id="footer">&copy; 2009 - <?php echo date("Y"); ?> Travis Crowder</div>
    </div>
  </body>
</html>