<?php
  echo $this->docType(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title><?php echo $this->title(); ?></title>
    <link rel="stylesheet" href="http://<?php echo $this->templatePath(); ?>/styles/style.css" type="text/css" media="screen" />
    <script type="text/javascript" src="http://<?php echo $this->templatePath(); ?>/scripts/js.js"></script>
  </head>
  <body>
    <div id="lynx_wrapper">
      <div id="header">Lynx RAD PHP Framework</div>
      <div id="content">
	    <?php
	       print_r(Lynx_Request::getInstance());
	      $this->renderPartial('index');
	    ?>
      </div>
      <div id="footer">&copy; 2009 - <?php echo date("Y"); ?> Travis Crowder</div>
    </div>
  </body>
</html>